# Generated by Django 4.1.4 on 2022-12-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='ip_address',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
