# Generated by Django 4.1.4 on 2022-12-26 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_alter_city_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set(),
        ),
    ]
